from typing import Union
from playwright.sync_api import sync_playwright, Locator, ElementHandle
import openai
from time import sleep

"""
Next steps:
    - [X] Create a structure that maps integer ids (generated by us) to Locator objects.
    - [X] Do something similar for simplified version of the elements
    - We send the simplified view, list of these elements to GPT.
    - GPT responds with ACTION and ID.
    - Where ACTION corresponds to actions we've implemented.
    - We perform the action on an element by grabbing it from our struct.
    - Since the struct contains `Locator`s, we can do the action on it directly using Playwright.

Later:
    - Internal monologue.
"""

class Crawler:
    def __init__(self):
        p = sync_playwright().start()
        self.browser = p.chromium.launch(headless=False)
        self.page = self.browser.new_page()
        self.elements_buffer: dict[int, Union[Locator, ElementHandle]] = {}
        self.simplified_elements_buffer: dict[int, str] = {}

    def go_to_page(self, url: str):
        self.page.goto(url)

    def add_elements_to_buffer(self):
        page_html = self.page.query_selector("body")
        links = page_html.query_selector_all("a")
        buttons = page_html.query_selector_all("button")
        images = page_html.query_selector_all("img")
        inputs = page_html.query_selector_all("input")

        i = 0
        for link in links:
            text = link.inner_text().strip().replace("\n", "").replace("  ", " ")
            if text == "":
                continue

            self.elements_buffer[i] = link
            self.simplified_elements_buffer[i] = "<link id={0}>{1}</link>".format(i, text)
            i += 1

        for button in buttons:
            text = button.inner_text().strip().replace("\n", "").replace("  ", " ")
            if text == "":
                continue

            self.elements_buffer[i] = button
            self.simplified_elements_buffer[i] = "<button id={0}>{1}</button>".format(i, text)
            i += 1

        for image in images:
            text = image.get_attribute("alt")
            if text == "":
                continue

            self.elements_buffer[i] = image
            self.simplified_elements_buffer[i] = "<img id={0} alt=\"{1}\" />".format(i, text)
            i += 1

        for input in inputs:
            t1 = input.get_attribute("title")
            t2 = input.get_attribute("alt")
            t3 = input.get_attribute("placeholder")
            t4 = input.get_attribute("aria-label")
            t5 = input.get_attribute("type")
            t6 = input.get_attribute("name")
            if t5 == "hidden": continue;

            print(t1, t2, t3, t4, t5, t6)
            text = t1 if t1 else " " + t2 if t2 else " " + t3 if t3 else " " + t4 if t4 else " " + t5 if t5 else " " + t6 if t6 else " "

            self.elements_buffer[i] = input
            self.simplified_elements_buffer[i] = "<input id={0} alt=\"{1}\" />".format(i, text)
            i += 1

if __name__ == "__main__":
    crawler = Crawler()
    crawler.go_to_page("https://wikipedia.com")
    crawler.add_elements_to_buffer()

    for i in (crawler.simplified_elements_buffer.values()):
        print(i)

    sleep(5)
    crawler.browser.close()
