from typing import Union
from playwright.sync_api import sync_playwright, Locator, ElementHandle
import openai
from time import sleep

"""
Next steps:
    - [X] Create a structure that maps integer ids (generated by us) to Locator objects.
    - We send the simplified view, list of these elements to GPT.
    - GPT responds with ACTION and ID.
    - Where ACTION corresponds to actions we've implemented.
    - We perform the action on an element by grabbing it from our struct.
    - Since the struct contains `Locator`s, we can do the action on it directly using Playwright.

Later:
    - Internal monologue.
"""

class Crawler:
    def __init__(self):
        p = sync_playwright().start()
        self.browser = p.chromium.launch(headless=False)
        self.page = self.browser.new_page()
        self.elements_buffer: dict[int, Union[Locator, ElementHandle]] = {}
        self.cleaned_elements_buffer: dict[int, Union[Locator, ElementHandle]] = {}

    def go_to_page(self, url: str):
        self.page.goto(url)

    def add_elements_to_buffer(self):
        page_html = self.page.query_selector("html")
        links = page_html.query_selector_all("a")
        buttons = page_html.query_selector_all("button")

        i = 0
        for link in links:
            self.elements_buffer[i] = link
            i += 1

        for button in buttons:
            self.elements_buffer[i] = button
            i += 1

    def clean_elements_buffer(self):
        for el in self.elements_buffer.values():
            print(el)

if __name__ == "__main__":
    crawler = Crawler()
    crawler.go_to_page("https://www.reddit.com")
    crawler.add_elements_to_buffer()
    print(crawler.elements_buffer)

    sleep(5)
    crawler.browser.close()
